language: java
jdk:
  - openjdk8

script:
  - gradle test

before_deploy:
  - gradle build

deploy:
  draft: true
  skip_cleanup: true
  provider: releases
  token: GH_TOKEN
  file: build/libs/*.jar
  on:
    tags: true