language: java
jdk:
  - oraclejdk8
  - openjdk8

script:
  - gradle test

before_deploy:
  - gradle build

deploy:
  cleanup: false
  provider: releases
  token: GH_TOKEN
  file: build/libs/*.jar
  on:
    tags: true